/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.26
 * Generated at: 2023-05-22 08:14:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("        <footer class=\"ft\">\r\n");
      out.write("            <article class=\"row row1\">\r\n");
      out.write("                <div class=\"ft_wrap\">\r\n");
      out.write("                    <nav class=\"fnb left\">\r\n");
      out.write("                        <ul class=\"fnb_box\">\r\n");
      out.write("                            <li><a href=\"pravacy.html\">개인정보처리방침</a></li>\r\n");
      out.write("                            <li><a href=\"usepromotion.html\">이용약관</a></li>\r\n");
      out.write("                            <li><a href=\"#\">법적고지</a></li>\r\n");
      out.write("                            <li><a href=\"#\">이메일 무단수집 거부</a></li>\r\n");
      out.write("                            <li><a href=\"#\">온라인 제보</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </nav>\r\n");
      out.write("                    <select name=\"favo\" id=\"favo\" class=\"favo right\" onchange=\"favo(this)\">\r\n");
      out.write("                        <option value=\"\">FAMILY SITE</option>\r\n");
      out.write("                        <option value=\"http://www.cj.net/\">CJ주식회사</option>\r\n");
      out.write("                        <option value=\"http://www.cj.co.kr/\">CJ제일제당</option>\r\n");
      out.write("                        <option value=\"https://www.cj.co.kr/kr/about/business/bio\">CJ바이오</option>\r\n");
      out.write("                        <option value=\"https://www.cjlogistics.com/ko/main\">CJ대한통운</option>\r\n");
      out.write("                        <option value=\"https://www.cjenm.com/ko/\">CJ ENM</option>\r\n");
      out.write("                        <option value=\"http://corp.cgv.co.kr/\">CJ CGV</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                    <script>\r\n");
      out.write("                    function favo(s){\r\n");
      out.write("                        var hs = s.value;\r\n");
      out.write("                        if(hs!=\"\"){\r\n");
      out.write("                            window.open(hs, \"팝업\");\r\n");
      out.write("                        }\r\n");
      out.write("                    }    \r\n");
      out.write("                    </script>\r\n");
      out.write("                </div>\r\n");
      out.write("            </article>\r\n");
      out.write("            <article class=\"row row2\">\r\n");
      out.write("                <div class=\"ft_wrap\">\r\n");
      out.write("                    <div class=\"slogan left\">\r\n");
      out.write("                        FOOD<br>\r\n");
      out.write("                        BUSINESS PARTNER<br>\r\n");
      out.write("                        CREATING<br>\r\n");
      out.write("                        THE SUCCESS WAY\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <nav class=\"ft_link_fr right\">\r\n");
      out.write("                        <dl class=\"ft_link item1\">\r\n");
      out.write("                            <dt>솔루션</dt>\r\n");
      out.write("                            <dd><a href=\"\">회사소개</a></dd>\r\n");
      out.write("                            <dd><a href=\"\">사업영역</a></dd>\r\n");
      out.write("                            <dd><a href=\"\">역량/인프라</a></dd>\r\n");
      out.write("                            <dd><a href=\"\">브랜드</a></dd>\r\n");
      out.write("                        </dl>\r\n");
      out.write("                        <dl class=\"ft_link item2\">\r\n");
      out.write("                            <dt>지속가능경영</dt>\r\n");
      out.write("                            <dd><a href=\"\">OVERVIEW</a></dd>\r\n");
      out.write("                            <dd><a href=\"\">전략</a></dd>\r\n");
      out.write("                            <dd><a href=\"\">주요활동 및 성과</a></dd>\r\n");
      out.write("                            <dd><a href=\"\">윤리경영</a></dd>\r\n");
      out.write("                            <dd><a href=\"\">사회공헌</a></dd>\r\n");
      out.write("                            <dd><a href=\"\">보고서 및 정책</a></dd>\r\n");
      out.write("                        </dl>\r\n");
      out.write("                        <dl class=\"ft_link item3\">\r\n");
      out.write("                            <dt>뉴스룸</dt>\r\n");
      out.write("                            <dd><a href=\"\">보도자료</a></dd>\r\n");
      out.write("                            <dd><a href=\"\">미디어</a></dd>\r\n");
      out.write("                            <dd><a href=\"\">홍보영상/브로슈어</a></dd>\r\n");
      out.write("                            <dd><a href=\"\">공지사항</a></dd>\r\n");
      out.write("                        </dl>\r\n");
      out.write("                        <dl class=\"ft_link item4\">\r\n");
      out.write("                            <dt>투자정보</dt>\r\n");
      out.write("                            <dd><a href=\"\">경영정보</a></dd>\r\n");
      out.write("                            <dd><a href=\"\">주가정보</a></dd>\r\n");
      out.write("                            <dd><a href=\"\">재무정보</a></dd>\r\n");
      out.write("                            <dd><a href=\"\">IR 자료실</a></dd>\r\n");
      out.write("                        </dl>\r\n");
      out.write("                        <dl class=\"ft_link item5\">\r\n");
      out.write("                            <dt>채용</dt>\r\n");
      out.write("                            <dd><a href=\"\">인사정보</a></dd>\r\n");
      out.write("                            <dd><a href=\"\">CJ프레시웨이 人SIDE</a></dd>\r\n");
      out.write("                            <dd><a href=\"\">채용정보</a></dd>\r\n");
      out.write("                            <dd><a href=\"\">인재 POOL</a></dd>\r\n");
      out.write("                        </dl>\r\n");
      out.write("                    </nav>\r\n");
      out.write("                </div>\r\n");
      out.write("            </article>\r\n");
      out.write("            <article class=\"row row3\">\r\n");
      out.write("                <div class=\"ft_wrap\">\r\n");
      out.write("                    <div class=\"ft_logo left\"></div>\r\n");
      out.write("                    <address class=\"copyright right\">서울시 마포구 월드컵북로 54길 25 S-city   COPYRIGHT© CJ FRESHWAY. ALL RIGHTS RESERVED.</address>\r\n");
      out.write("                </div>\r\n");
      out.write("            </article>\r\n");
      out.write("        </footer>\r\n");
      out.write("    <div class=\"fix_area\">\r\n");
      out.write("        <a href=\"#page5\" class=\"cir_box counsel\">고객<br>상담센터</a>\r\n");
      out.write("        <a href=\"#\" class=\"cir_box totop\">↑<br>TOP</a>\r\n");
      out.write("    </div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
